version: "2"

services:
  web:
    build: .
    depends_on:
      - redis
      - db
    volumes:
      - ".:/app"
    environment:
      CACHE_URL: redis://redis:6379
      SECRET_KEY: notsosecret
      DATABASE_URL: postgres://web:secretpassword@db:5432/web
  redis:
    image: redis:3.2
    expose:
      - "6379"
  db:
    image: postgres:9.4
    volumes:
      - "db:/var/lib/postgres/data"
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: secretpassword
  lb:
    image: dockercloud/haproxy:1.5.2
    links:
      - web
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    ports:
      - "80:80"

volumes:
  db:
    driver: local
